import numpy as n
import string as s

# ------------------------- setting up -------------------------
#   space   +        letters a-z    +        numbers 0-9
O = [' '] + list(s.ascii_lowercase) + [str(i) for i in range(10)]
mat1 = n.array([[1], [1], [1]])

def encrypt_message(key, message):
    """
    Encrypts a message using matrix transformations.
    Args:
        key (int): The numeric key.
        message (str): The message to encrypt.
    Returns:
        tuple: (encrypted_message_str, H_values_list)
    """
    message = message.lower()
    m_list = list(message)
    maty = []

    # Map characters to vectors
    for char in m_list:
        if char in O: # Only process valid characters
            i = O.index(char)
            # Logic from user's code: [i, 2*i + j + key, 2*i + 2*j]
            # But wait, 'j' in user's loop was index of char in message.
            j = m_list.index(char) 
            # CAUTION: user code used `for j in range(len(m)): ... if O[i] == m[j]:`
            # This logic in the user's code is slightly flawed if there are duplicate characters,
            # because `j` is the loop index, which is correct.
            # My list comprehension above `m_list.index(char)` would find the FIRST occurrence, which is WRONG for the formula if j matters.
            # let's rewrite to match user structure safely.
            pass

    # Correct Loop implementation
    maty = []
    for j in range(len(m_list)):
        char = m_list[j]
        if char in O:
            i = O.index(char)
            A = [i, 2*i + j + key, 2*i + 2*j]
            maty.append(A)
        else:
            # Handle standard characters not in O? User code ignored them or probably errored/didn't handle.
            # We will ignore them for now to match user logic, or append a dummy?
            # User code: `for i in range(len(O)): if O[i] == m[j]:` implies it skips if not found.
            # If it skips, then `maty` length != `m` logic might get desynced if we use j later?
            # Actually user code builds `maty` only for found chars.
            pass

    if not maty:
        return "", []

    # Matrix multiplication
    # maty is (N, 3), mat1 is (3, 1) -> res is (N, 1)
    res = n.dot(maty, mat1)
    
    # Flatten result
    f = [item for sublist in res.tolist() for item in sublist]

    # Modulo operation
    H = []
    mod_base = len(O)
    processed_f = []
    
    for val in f:
        H.append(val // mod_base)
        processed_f.append(val % mod_base)

    # Map back to characters
    encrypted_chars = []
    for val in processed_f:
        if 0 <= val < len(O):
            encrypted_chars.append(O[val])
            
    return "".join(encrypted_chars), H

def decrypt_message(key, encrypted_text, H_values):
    """
    Decrypts a message.
    Args:
        key (int): The numeric key.
        encrypted_text (str): The encrypted message.
        H_values (list[int]): The list of H values.
    Returns:
        str: Decrypted message.
    """
    # User instruction: "enter encrypted text".lower()
    # But encrypted text usually needs to be exact? 
    # User code lowered input `m = input(...).lower()`. 
    # `encrypted` output was `"".join(F)` where `F` came from `O`. `O` has space + lowercase + numbers.
    # So lowercase is fine, but numbers/spaces should be preserved.
    
    m = list(encrypted_text)
    
    if len(m) != len(H_values):
        raise ValueError("Length of encrypted text and H values must match.")

    # Reconstruct numeric values
    # Users code: `a = i + len(O) * H[j]`
    A = []
    for j in range(len(m)):
        char = m[j]
        if char in O:
            i = O.index(char)
            a = i + len(O) * H_values[j]
            A.append(a)
        else:
            # Encrypted text shouldn't have invalid chars if generated by us
            pass
            
    # Reverse transformation
    # User code: `f = (A[j] - 3*j - key) // 5`
    # Wait, where did `5` come from? 
    # Encryption: `A = [i, 2*i + j + key, 2*i + 2*j]`
    # Dot product with [1,1,1]: `sum = i + (2i + j + key) + (2i + 2j) = 5i + 3j + key`
    # So `5i = sum - 3j - key` => `i = (sum - 3j - key) / 5`
    # Math checks out.
    
    F = []
    for j in range(len(A)):
        val = (A[j] - 3*j - key) / 5
        # It should be an integer result
        F.append(int(val))

    # Map back
    decrypted_chars = []
    for val in F:
        if 0 <= val < len(O):
            decrypted_chars.append(O[val])
            
    return "".join(decrypted_chars)
